swipe:
  3:
    left:
      sendkey: 'LEFTALT+RIGHT'
    right:
      sendkey: 'LEFTALT+LEFT'
    up:
      sendkey: 'LEFTCTRL+T'
    down:
      sendkey: 'LEFTCTRL+W'
pinch:
  2:
    in:
      sendkey: 'LEFTCTRL+EQUAL'
      threshold: 0.1
    out:
      sendkey: 'LEFTCTRL+MINUS'
      threshold: 0.1
  4:
    in:
      command: "dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'if (Main.overview.visible && Main.overview.viewSelector._showAppsButton.checked) { Main.overview.hide();Main.overview.viewSelector._showAppsButton.checked=false;} else {Main.overview.show()}'"
      threshold: 1
      interval: 2
    out:
      command: "dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'if (Main.overview.visible && !Main.overview.viewSelector._showAppsButton.checked) {Main.overview.hide()} else { Main.overview.viewSelector._showAppsButton.checked = true;Main.overview.show();}'"
      threshold: 1
      interval: 2
      
threshold:
  swipe: 0.3
  pinch: 1

interval:
  swipe: 1
  pinch: 1
