# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:hack 9

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec kitty

# kill focused window
bindsym $mod+q kill
bindsym XF86AudioRaiseVolume exec amixer -q set Master 2dB+ unmute
bindsym XF86AudioLowerVolume exec amixer -q set Master 2dB- unmute
bindsym XF86AudioMute exec amixer -q set Master toggle

bindsym $mod+d exec --no-startup-id "rofi -combi-modi window,drun -font 'hack 30' -show combi"

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Ctrl+h move left
bindsym $mod+Ctrl+j move down
bindsym $mod+Ctrl+k move up
bindsym $mod+Ctrl+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Ctrl+Left move left
bindsym $mod+Ctrl+Down move down
bindsym $mod+Ctrl+Up move up
bindsym $mod+Ctrl+Right move right

# split in horizontal orientation
bindsym $mod+g split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+Ctrl+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
# bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+s layout stacked
bindsym $mod+e layout toggle split
# workspace_layout tabbed


# focus the parent container
bindsym $mod+p focus parent

# focus the child container
bindsym $mod+c focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.  set $ws1 "1"
set $ide "1: ide"
set $web "2: web"
set $other "3: chat"

# switch to workspace
bindsym $mod+i workspace number $ide
bindsym $mod+w workspace number $web
bindsym $mod+o workspace number $other

bindsym $mod+1 workspace number $ide
bindsym $mod+2 workspace number $web
bindsym $mod+3 workspace number $other

# move focused container to workspace
bindsym $mod+Ctrl+i move container to workspace number $ide
bindsym $mod+Ctrl+w move container to workspace number $web
bindsym $mod+Ctrl+slash move container to workspace number $term
bindsym $mod+Ctrl+o move container to workspace number $other
bindsym $mod+Ctrl+c move container to workspace number $chat

bindsym $mod+Ctrl+1 move container to workspace number $ide
bindsym $mod+Ctrl+2 move container to workspace number $web
bindsym $mod+Ctrl+3 move container to workspace number $term
bindsym $mod+Ctrl+4 move container to workspace number $other
bindsym $mod+Ctrl+5 move container to workspace number $chat

workspace_auto_back_and_forth yes

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Make the currently focused window a scratchpad
bindsym $mod+Ctrl+backslash move scratchpad
# Show the first scratchpad window
bindsym $mod+backslash scratchpad show

# toggle tiling / floating
bindsym $mod+f floating toggle
# change focus between tiling / floating windows
bindsym $mod+Shift+f focus mode_toggle

# >>> Plasma Integration <<<

# Try to kill the wallpaper set by Plasma (it takes up the entire workspace
# and hides everythiing)

exec --no-startup-id nitrogen --restore
exec --no-startup-id setxkbmap -model pc105 -layout us,ru -option caps:super,grp:win_space_toggle,ctrl:swap_lalt_lctl
exec --no-startup-id compton -b
exec --no-startup-id xinput --disable 14

# class                 border  bground text    indicator child_border
client.focused          #ffaf00 #ffaf00 #f8f8f8 #5c5c5c   #5c5c5c
client.focused_inactive #0087ff #0087ff #f8f8f8 #5c5c5c   #5c5c5c
client.unfocused        #5c5c5c #5c5c5c #f8f8f8 #5c5c5c   #5c5c5c
client.urgent           #FF5555 #FF5555 #f8f8f8 #FF5555   #FF5555
client.placeholder      #5c5c5c #5c5c5c #f8f8f8 #5c5c5c   #5c5c5c

client.background       #5c5c5c

#for_window [class="^.*"] border pixel 0

bar {
  status_command i3blocks
    colors {
      background #5c5c5c
        statusline #f8f8f8
        separator  #ffaf00
        focused_workspace  #5c5c5c #ffaf00 #5c5c5c
        active_workspace   #5c5c5c #0087ff #5c5c5c
        inactive_workspace #5c5c5c #5c5c5c #BFBFBF
        urgent_workspace   #FF5555 #FF5555 #5c5c5c
        binding_mode       #FF5555 #FF5555 #5c5c5c
    }
}

