# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:hack 9

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec kitty tmux new-session

# kill focused window
bindsym $mod+q kill

# start dmenu (a program launcher)
#bindsym $mod+d exec dmenu_run
#bindsym $mod+d exec i3-dmenu-desktop
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.

bindsym $mod+d exec --no-startup-id "rofi -combi-modi window,drun -show combi -modi combi"

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Ctrl+h move left
bindsym $mod+Ctrl+j move down
bindsym $mod+Ctrl+k move up
bindsym $mod+Ctrl+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Ctrl+Left move left
bindsym $mod+Ctrl+Down move down
bindsym $mod+Ctrl+Up move up
bindsym $mod+Ctrl+Right move right

# split in horizontal orientation
bindsym $mod+g split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
# bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
# bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+s layout stacked
bindsym $mod+e layout toggle split
workspace_layout stacked

# toggle tiling / floating
bindsym $mod+Ctrl+f floating toggle

# change focus between tiling / floating windows
bindsym $mod+f focus mode_toggle

# focus the parent container
#bindsym $mod+p focus parent

# focus the child container
#bindsym $mod+c focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.  set $ws1 "1"
set $ws1 "1: ide"
set $ws2 "2: web"
set $ws3 "3: chat"
set $ws4 "4: other"
set $terminal "5"

# switch to workspace
bindsym $mod+i workspace number $ws1
bindsym $mod+w workspace number $ws2
bindsym $mod+c workspace number $ws3
bindsym $mod+o workspace number $ws4
bindsym $mod+slash workspace number $terminal

bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $terminal

# move focused container to workspace
bindsym $mod+Ctrl+i move container to workspace number $ws1
bindsym $mod+Ctrl+w move container to workspace number $ws2
bindsym $mod+Ctrl+c move container to workspace number $ws3
bindsym $mod+Ctrl+o move container to workspace number $ws4
bindsym $mod+Ctrl+slash move container to workspace number $ws4

bindsym $mod+Ctrl+1 move container to workspace number $ws1
bindsym $mod+Ctrl+2 move container to workspace number $ws2
bindsym $mod+Ctrl+3 move container to workspace number $ws3
bindsym $mod+Ctrl+4 move container to workspace number $ws4
bindsym $mod+Ctrl+5 move container to workspace number $terminal

workspace_auto_back_and_forth yes

#for_window [class="kitty-full"] fullscreen enable
#
#set $ws1 "1"
#set $ws2 "2"
#set $ws3 "1"
#set $ws4 "2"
#set $ws5 "5"
#set $ws6 "6"
#set $ws7 "7"
#set $ws8 "8"
#set $ws9 "9"
#
## switch to workspace
#bindsym $mod+1 workspace $ws1
#bindsym $mod+2 workspace $ws2
#bindsym $mod+3 workspace $ws3
#bindsym $mod+4 workspace $ws4
#bindsym $mod+5 workspace $ws5
#bindsym $mod+6 workspace $ws6
#bindsym $mod+7 workspace $ws7
#bindsym $mod+8 workspace $ws8
#bindsym $mod+9 workspace $ws9
#
## move focused container to workspace
#bindsym $mod+Ctrl+1 move container to workspace $ws1
#bindsym $mod+Ctrl+2 move container to workspace $ws2
#bindsym $mod+Ctrl+3 move container to workspace $ws3
#bindsym $mod+Ctrl+4 move container to workspace $ws4
#bindsym $mod+Ctrl+5 move container to workspace $ws5
#bindsym $mod+Ctrl+6 move container to workspace $ws6
#bindsym $mod+Ctrl+7 move container to workspace $ws7
#bindsym $mod+Ctrl+8 move container to workspace $ws8
#bindsym $mod+Ctrl+9 move container to workspace $ws9

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Make the currently focused window a scratchpad
bindsym $mod+Ctrl+backslash move scratchpad
# Show the first scratchpad window
bindsym $mod+backslash scratchpad show

# >>> Plasma Integration <<<

# Try to kill the wallpaper set by Plasma (it takes up the entire workspace
# and hides everythiing)

exec --no-startup-id nitrogen --restore
exec --no-startup-id setxkbmap -model pc105 -layout us,ru -option caps:super,grp:win_space_toggle,ctrl:swap_lalt_lctl
exec --no-startup-id compton --vsync opengl


# class                 border  bground text    indicator child_border
client.focused          #ffaf00 #ffaf00 #1c1c1c #ffffff   #ffffff
client.focused_inactive #0087ff #0087ff #f8f8f2 #f8f8f2   #f8f8f2
client.unfocused        #f8f8f2 #f8f8f2 #5c5c5c #f8f8f2   #f8f8f2
client.urgent           #FF5555 #FF5555 #1c1c1c #FF5555   #FF5555
client.placeholder      #f8f8f2 #f8f8f2 #1c1c1c #f8f8f2   #f8f8f2

client.background       #ffffff

#for_window [class="^.*"] border pixel 0

bar {
  status_command i3blocks
    colors {
      background #f8f8f2
        statusline #5c5c5c
        separator  #ffaf00
        focused_workspace  #f8f8f2 #ffaf00 #000000
        active_workspace   #f8f8f2 #0087ff #f8f8f2
        inactive_workspace #f8f8f2 #f8f8f2 #BFBFBF
        urgent_workspace   #FF5555 #FF5555 #ffffff
        binding_mode       #FF5555 #FF5555 #ffffff
    }
}

