name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
      - 'release-**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  # Interrupt this workflow for new launches from the development branch.
  # For launches from the main branch, wait until previous instances complete.
  # @SEE: https://github.com/tarantool/message-queue-ee/pull/239
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  pack:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-')
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "pack" $(git describe --tags)
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    # needs: 
      # - pack
    timeout-minutes: 50
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "release" $(git describe --tags)
