name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
      - 'release-**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  # Interrupt this workflow for new launches from the development branch.
  # For launches from the main branch, wait until previous instances complete.
  # @SEE: https://github.com/tarantool/message-queue-ee/pull/239
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v3
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "TEST" $(git describe --tags)
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 15
    outputs:
      DEST_PATH: ${{steps.set-environment.outputs.DEST_PATH}}
    needs:
      - test
    steps:
      - name: Set dev/release environment
        id: set-environment
        run: |
          if ${{ github.ref_type == 'tag' }}; then
            echo "DEST_PATH="${{ needs.publish-artifacts.outputs.DEST_PATH }}">> $GITHUB_OUTPUT
          else
            echo "DEST_PATH="s3://packages/message-queue-ee/release/linux/x86_64/${{ env.VERSION }}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "PUBLISH TO ${{ steps.set-environment.outputs.DEST_PATH}}" $(git describe --tags)
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 15
    needs: publish
    steps:
      - run: |
          echo "VALIDATE FROM ${{needs.publish.outputs.DEST_PATH}}"

