name: Continuous Integration

on:
  pull_request:
  push:
    # branches:
    #   - master
    #   - 'release-**'
    # tags:
    #   - '[0-9]+.[0-9]+.[0-9]+'

# concurrency:
#   # Interrupt this workflow for new launches from the development branch.
#   # For launches from the main branch, wait until previous instances complete.
#   # @SEE: https://github.com/tarantool/message-queue-ee/pull/239
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v3
  test:
    # pr + main + release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "TEST" $(git describe --tags)
  pack:
    # main + release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 15
    needs:
      - test
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "PACK" $(git describe --tags)
  release:
    # release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: 
      - pack
    timeout-minutes: 50
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v4
      - run: |
          echo "RELEASE" $(git describe --tags)
