name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'release-**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  # Interrupt this workflow for new launches from the development branch.
  # For launches from the main branch, wait until previous instances complete.
  # @SEE: https://github.com/tarantool/message-queue-ee/pull/239
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pack:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-')
    timeout-minutes: 15
    steps:
      - run: echo "pack"
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: 
      - pack
    timeout-minutes: 50
    steps:
      - run: echo "release"