---
name: 'Release'
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 1
        run: |
          echo 'Release'
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}