---
name: 'Release'
on:
  push:
    tags: '*'

env:
  IMAGE: registry.gitlab.com/tarantool/feedback

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo 'Release'
          echo $IMAGE:$RELEASE_VERSION